- name: instalando o puppetserver
  package:
   name: puppetserver
   update_cache: yes
  when: ansible_hostname == "devops"


- name: instalando o puppet agente
  package:
   name: puppet-agent
   update_cache: yes
