- name: instalando o servidor web
  package:
   name: "{{item.nome}}"
  when: ansible_os_family == item.distro
  with_items:
    - { nome: apache2, distro: "Debian" }
    - { nome: http2, distro: "RedHat" }
  notify: start_centos
