- name: criando um loop
  hosts: all
  tasks:
   - name: instalando pacotes
     yum:
      name: epel-release
     when: ansible_os_family == "RedHat"

   - name: instalando pacote
     package:
      name: "{{ item }}"
     with_items:
       - vim
       - cowsay
       - figlet 
